{"tags": ["django", "mongodb", "pymongo"], "comments": [{"post_id": 15940220, "comment_id": 22711741, "body": "Did you install it by <code>sudo apt-get install python-pymongo</code>?"}, {"post_id": 15940220, "comment_id": 22712128, "body": "No, I used pip install pymongo. I just tried installing it with sudo apt-get, and that works, but now i can&#39;t import it from the virtualenv"}, {"post_id": 15940220, "comment_id": 22712157, "body": "If you run <code>pip freeze</code>, is mongo in that list?"}, {"post_id": 15940220, "comment_id": 22712158, "body": "Um nevermind. I&#39;m an idiot. It works only when installed with apt-get AND pip through the virtualenv. Thanks Joe. And thanks for telling me about pip freeze, that gave me a bunch of free xp."}, {"post_id": 15940220, "comment_id": 22788138, "body": "mongoDB doesn&#39;t work with Django. You need to use django-nonrel. Can you syncdb? what verison of django, pymongo, mongodb are you using?"}, {"post_id": 15940220, "comment_id": 22789380, "body": "I haven&#39;t figured out how to integrate mongo with django yet, I&#39;ll look into django-norel. I&#39;m doing it the &quot;stupid way&quot; for now, where I just make inserts manually from the python code by importing pymongo and inserting into the relevant collection based on the URL of the POST request."}, {"post_id": 15940220, "comment_id": 22789387, "body": "mongodb version v2.4.1, pymongo 2.1, and django 1.4.1"}], "answers": [{"answer_id": 25383224, "question_id": 15940220, "body": "<p>This error happened to me after <code>pip install</code> (in virtualenv) both <code>pymongo</code> and <code>bson</code>. </p>\n\n<p>Uninstall <code>pymongo</code> and <code>bson</code> and install again just <code>pymongo</code> - it ships with its own version of <code>bson</code> not compatible with the <code>bson</code> package.</p>\n\n<p><a href=\"https://stackoverflow.com/a/12983651/196206\">https://stackoverflow.com/a/12983651/196206</a></p>\n"}, {"answer_id": 68685144, "question_id": 15940220, "body": "<p>I have solved the problem with uninstall  pymongo and again install with the following command:\npython -m pip install pymongo</p>\n"}], "is_answered": true, "answer_count": 2, "last_activity_date": 1628268989, "question_id": 15940220, "title": "Error importing pymongo in my django app", "body": "<p>I'm trying to insert documents into mongodb from django and I'm getting an error on the import statement for pymongo. I don't have a duplicate file anywhere called pymongo and I'm pretty sure my virtualenv is set up correctly.</p>\n\n<pre><code>(django-sample-app)ubuntu@django (884) ~ $ python\n\nPython 2.7.3 (default, Aug  1 2012, 05:14:39) \n\n[GCC 4.6.3] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n\n&gt;&gt;&gt; import bson\n\n&gt;&gt;&gt; import pymongo\n\nTraceback (most recent call last):\n  File \"&lt;stdin&gt;\", line 1, in &lt;module&gt;\n  File \"/home/ubuntu/.virtualenvs/django-sample-app/local/lib/python2.7/site-packages/pymongo/__init__.py\", line 80, in &lt;module&gt;\n    from pymongo.connection import Connection\n  File \"/home/ubuntu/.virtualenvs/django-sample-app/local/lib/python2.7/site-packages/pymongo/connection.py\", line 39, in &lt;module&gt;\n    from pymongo.mongo_client import MongoClient\n  File \"/home/ubuntu/.virtualenvs/django-sample-app/local/lib/python2.7/site-packages/pymongo/mongo_client.py\", line 45, in &lt;module&gt;\n    from pymongo import (auth,\n  File \"/home/ubuntu/.virtualenvs/django-sample-app/local/lib/python2.7/site-packages/pymongo/database.py\", line 22, in &lt;module&gt;\n    from pymongo.collection import Collection\n  File \"/home/ubuntu/.virtualenvs/django-sample-app/local/lib/python2.7/site-packages/pymongo/collection.py\", line 25, in &lt;module&gt;\n    from pymongo.cursor import Cursor\n  File \"/home/ubuntu/.virtualenvs/django-sample-app/local/lib/python2.7/site-packages/pymongo/cursor.py\", line 19, in &lt;module&gt;\n    from bson import RE_TYPE\nImportError: cannot import name RE_TYPE\n</code></pre>\n"}