{
    "items": [
      {
        "tags": [
          "python",
          "django",
          "docker"
        ],
        "comments": [
          {
            "post_id": 68384185,
            "comment_id": 120857059,
            "body": "What do you see if you add verbosity (<code>-v</code>) to the pip command?"
          },
          {
            "post_id": 68384185,
            "comment_id": 120857061,
            "body": "Try to add <code>-v</code> or even <code>-vv</code> to your <code>pip</code> call to get more debugging details."
          },
          {
            "post_id": 68384185,
            "comment_id": 120857141,
            "body": "Thanks both. I made the change and update the post with the results"
          },
          {
            "post_id": 68384185,
            "comment_id": 120857239,
            "body": "I saw the HTTPS timeout and restarted my OS, that seems to have resolved the issue and the build was successful. Not sure exactly what the issue really was. Thanks both for your help anyway! Verbosity for the win"
          }
        ],
        "answers": [
          {
            "answer_id": 68385313,
            "question_id": 68384185,
            "body": "<p>It seems that the reason is in virtual environment and the way how you want to hack it with <code>scripts</code> folder.</p>\n<p>You don't necessary need to create virtual env inside docker as it is already isolated inside container.\nTry to do same but without virtualenv in <code>Dockerfile</code></p>\n<pre><code>FROM python:3.9-alpine3.14\nLABEL maintainer=&quot;superapp&quot;\n\nENV PYTHONUNBUFFERED 1\n\nCOPY requirements.txt /requirements.txt\nCOPY app /app\nWORKDIR /app\n\nRUN pip install --upgrade pip &amp;&amp; \\\n    apk add --update --no-cache --virtual .build-deps \\\n    build-base \\\n    gcc \\\n    linux-headers &amp;&amp; \\\n    pip install -r /requirements.txt &amp;&amp; \\\n    apk del .build-deps &amp;&amp; \\\n    adduser --disabled-password --no-create-home rsecuser &amp;&amp; \\\n    mkdir -p /vol/web/static &amp;&amp; \\\n    chown -R rsecuser:rsecuser /vol &amp;&amp; \\\n    chmod -R 755 /vol\n\nUSER rsecuser\nEXPOSE 8000\n\nCMD [&quot;run.sh&quot;]\n</code></pre>\n"
          },
          {
            "answer_id": 68385425,
            "question_id": 68384185,
            "body": "<p>I've done some modification if ur code and it worked for me.\nTry to execute :<br />\ndocker build .</p>\n<pre><code>FROM python:3.9-alpine3.14\nLABEL maintainer=&quot;superapp&quot;\n\nENV PYTHONUNBUFFERED 1\n\nRUN mkdir /app\n\nWORKDIR /app\nCOPY ./app /app\n\nCOPY ./scripts /scripts\nCOPY requirements.txt /requirements.txt\nRUN pip install --upgrade pip &amp;&amp; \\\n    apk add --update --no-cache --virtual .build-deps \\\n    build-base \\\n    gcc \\\n    linux-headers &amp;&amp; \\\n    pip install -r /requirements.txt &amp;&amp; \\\n    apk del .build-deps &amp;&amp; \\\n    adduser --disabled-password --no-create-home rsecuser &amp;&amp; \\\n    mkdir -p /vol/web/static &amp;&amp; \\\n    chown -R rsecuser:rsecuser /vol &amp;&amp; \\\n    chmod -R 755 /vol &amp;&amp; \\\n    chmod -R +x /scripts\n\nUSER rsecuser\nEXPOSE 8000\n\nCMD [&quot;run.sh&quot;]\n\n</code></pre>\n"
          }
        ],
        "is_answered": false,
        "answer_count": 2,
        "last_activity_date": 1626299169,
        "question_id": 68384185,
        "title": "Django version not found when running docker-compose with python3.9 alpine image",
        "body": "<p>Hi I'm trying to build out a basic app django within a python/alpine image.</p>\n<p>I am getting en error telling me that there is no matching image for the version of Django that I am looking for.</p>\n<p>The Dockerfile in using a <code>python:3.9-alpine3.14</code> image and my requirements file is targeting <code>Django&gt;=3.2.5,&lt;3.3</code>.</p>\n<p>From what i understand these should be compatible, Django &gt;= 3 and Python 3.9.</p>\n<p>When I run <code>docker-compose build</code> the RUN command gets so far as the <code>apk add</code> commands but fails on <code>pip</code>. I did try changing this to <code>pip3</code> but this had no effect.</p>\n<p>Any idea what I am missing here that will fix this issue?</p>\n<p><code>requirements.txt</code></p>\n<pre><code>Django&gt;=3.2.5,&lt;3.3\nuWSGI&gt;=2.0.19.1,&lt;2.1\n</code></pre>\n<p><code>Dockerfile</code></p>\n<pre><code>FROM python:3.9-alpine3.14\nLABEL maintainer=&quot;superapp&quot;\n\nENV PYTHONUNBUFFERED 1\n\nCOPY requirements.txt /requirements.txt\nRUN mkdir /app\nCOPY ./app /app\nCOPY ./scripts /scripts\nWORKDIR /app\n\nEXPOSE 8000\n\nRUN python -m venv /py &amp;&amp; \\\n    /py/bin/pip install --upgrade pip &amp;&amp; \\\n    apk add --update --no-cache --virtual .build-deps \\\n    build-base \\\n    gcc \\\n    linux-headers &amp;&amp; \\\n    /py/bin/pip install -r /requirements.txt &amp;&amp; \\\n    apk del .build-deps &amp;&amp; \\\n    adduser --disabled-password --no-create-home rsecuser &amp;&amp; \\\n    mkdir -p /vol/web/static &amp;&amp; \\\n    chown -R rsecuser:rsecuser /vol &amp;&amp; \\\n    chmod -R 755 /vol &amp;&amp; \\\n    chmod -R +x /scripts\n\nENV PATH=&quot;/scripts:/py/bin:$PATH&quot;\n\nUSER rsecuser\n\nCMD [&quot;run.sh&quot;]\n</code></pre>\n<p><code>docker-compose.yml</code></p>\n<pre><code>version: &quot;3.9&quot;\n\nservices:\n  app:\n    build:\n      context: .\n    command: &gt;\n      sh -c &quot;python manage.py runserver 0.0.0.0:8000&quot;\n    ports:\n      - 8000:8000\n    volumes:\n      - ./app:/app\n      - ./data/web:/vol/web\n    environment: \n      - SECRET_KEY=development_key\n      - DEBUG=1\n</code></pre>\n<p>Error</p>\n<pre><code>...\n...\n...\n(20/22) Installing build-base (0.5-r2)\n(21/22) Installing linux-headers (5.10.41-r0)\n(22/22) Installing .build-deps (20210714.193049)\nExecuting busybox-1.33.1-r2.trigger\nOK: 212 MiB in 58 packages\nERROR: Could not find a version that satisfies the requirement Django&lt;3.3,&gt;=3.2.5 (from versions: none)\nERROR: No matching distribution found for Django&lt;3.3,&gt;=3.2.5\nERROR: Service 'app' failed to build : The command '/bin/sh -c python -m venv /py &amp;&amp;     /py/bin/pip install --upgrade pip &amp;&amp;     apk add --update --no-cache --virtual .build-deps     build-base     gcc     linux-headers &amp;&amp;     /py/bin/pip install -r /requirements.txt &amp;&amp;     apk del .build-deps &amp;&amp;     adduser --disabled-password --no-create-home rsecuser &amp;&amp;     mkdir -p /vol/web/static &amp;&amp;     chown -R rsecuser:rsecuser /vol &amp;&amp;     chmod -R 755 /vol &amp;&amp;     chmod -R +x /scripts' returned a non-zero code: 1(20/22) Installing build-base (0.5-r2)\n(21/22) Installing linux-headers (5.10.41-r0)\n(22/22) Installing .build-deps (20210714.193049)\nExecuting busybox-1.33.1-r2.trigger\nOK: 212 MiB in 58 packages\nERROR: Could not find a version that satisfies the requirement Django&lt;3.3,&gt;=3.2.5 (from versions: none)\nERROR: No matching distribution found for Django&lt;3.3,&gt;=3.2.5\nERROR: Service 'app' failed to build : The command '/bin/sh -c python -m venv /py &amp;&amp;     /py/bin/pip install --upgrade pip &amp;&amp;     apk add --update --no-cache --virtual .build-deps     build-base     gcc     linux-headers &amp;&amp;     /py/bin/pip install -r /requirements.txt &amp;&amp;     apk del .build-deps &amp;&amp;     adduser --disabled-password --no-create-home rsecuser &amp;&amp;     mkdir -p /vol/web/static &amp;&amp;     chown -R rsecuser:rsecuser /vol &amp;&amp;     chmod -R 755 /vol &amp;&amp;     chmod -R +x /scripts' returned a non-zero code: 1\n</code></pre>\n<p>As per comments below, same command run with <code>/py/bin/pip -vv install -r /requirements.txt</code> in the Dockerfile.</p>\n<pre><code>(21/22) Installing linux-headers (5.10.41-r0)\n(22/22) Installing .build-deps (20210714.195119)\nExecuting busybox-1.33.1-r2.trigger\nOK: 212 MiB in 58 packages\nUsing pip 21.1.3 from /py/lib/python3.9/site-packages/pip (python 3.9)\nNon-user install because user site-packages disabled\nCreated temporary directory: /tmp/pip-ephem-wheel-cache-gyetbpa_\nCreated temporary directory: /tmp/pip-req-tracker-og42yr4p\nInitialized build tracking at /tmp/pip-req-tracker-og42yr4p\nCreated build tracker: /tmp/pip-req-tracker-og42yr4p\nEntered build tracker: /tmp/pip-req-tracker-og42yr4p\nCreated temporary directory: /tmp/pip-install-p5b3_acb\n1 location(s) to search for versions of django:\n* https://pypi.org/simple/django/\nFetching project page and analyzing links: https://pypi.org/simple/django/\nGetting page https://pypi.org/simple/django/\nFound index url https://pypi.org/simple\nLooking up &quot;https://pypi.org/simple/django/&quot; in the cache\nRequest header has &quot;max_age&quot; as 0, cache bypassed\nStarting new HTTPS connection (1): pypi.org:443\nhttps://pypi.org:443 &quot;GET /simple/django/ HTTP/1.1&quot; 200 42407\nCould not fetch URL https://pypi.org/simple/django/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. - skipping\nSkipping link: not a file: https://pypi.org/simple/django/\nGiven no hashes to check 0 links for project 'django': discarding no candidates\nERROR: Could not find a version that satisfies the requirement Django&lt;3.3,&gt;=3.2.5 (from versions: none)\nERROR: No matching distribution found for Django&lt;3.3,&gt;=3.2.5\nException information:\nTraceback (most recent call last):\n  File &quot;/py/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py&quot;, line 341, in resolve\n    name, crit = self._merge_into_criterion(r, parent=None)\n  File &quot;/py/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py&quot;, line 173, in _merge_into_criterion\n    raise RequirementsConflicted(criterion)\npip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('Django&lt;3.3,&gt;=3.2.5')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/py/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py&quot;, line 127, in resolve\n    result = self._result = resolver.resolve(\n  File &quot;/py/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py&quot;, line 473, in resolve\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\n  File &quot;/py/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py&quot;, line 343, in resolve\n    raise ResolutionImpossible(e.criterion.information)\npip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('Django&lt;3.3,&gt;=3.2.5'), parent=None)]\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/py/lib/python3.9/site-packages/pip/_internal/cli/base_command.py&quot;, line 180, in _main\n    status = self.run(options, args)\n  File &quot;/py/lib/python3.9/site-packages/pip/_internal/cli/req_command.py&quot;, line 205, in wrapper\n    return func(self, options, args)\n  File &quot;/py/lib/python3.9/site-packages/pip/_internal/commands/install.py&quot;, line 318, in run\n    requirement_set = resolver.resolve(\n  File &quot;/py/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py&quot;, line 136, in resolve\n    raise error from e\npip._internal.exceptions.DistributionNotFound: No matching distribution found for Django&lt;3.3,&gt;=3.2.5\nRemoved build tracker: '/tmp/pip-req-tracker-og42yr4p'\nERROR: Service 'app' failed to build : The command '/bin/sh -c python -m venv /py &amp;&amp;     /py/bin/pip install --upgrade pip &amp;&amp;     apk add --update --no-cache --virtual .build-deps     build-base     gcc     linux-headers &amp;&amp;     /py/bin/pip -vv install -r /requirements.txt &amp;&amp;     apk del .build-deps &amp;&amp;     adduser --disabled-password --no-create-home rsecuser &amp;&amp;     mkdir -p /vol/web/static &amp;&amp;     chown -R rsecuser:rsecuser /vol &amp;&amp;     chmod -R 755 /vol &amp;&amp;     chmod -R +x /scripts' returned a non-zero code: 1\n</code></pre>\n"
      }
    ],
    "has_more": false,
    "quota_max": 10000,
    "quota_remaining": 9661
  }